import '../globals.css';
import './tostify.css';

import Header from '@components/header/header';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import React from 'react';

// eslint-disable-next-line new-cap
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App',
};

export default function RootLayout({
    children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body 
                className={[
                    inter.className,
                    'max-w-[3840px]',
                    'mx-auto',
                    'break-all',
                    ['bg-neutral-200 dark:bg-neutral-900'].join(' '),
                    ['text-neutral-950 dark:text-neutral-50'].join(' ')
                	].join(' ')
            	}
            >
                <Header />
                <main 
                    className={[
                        'mt-24 md:mt-32', 
                        'md:mx-16', 
                        'md:mb-16'
                    ].join(' ')
                    }
                >
                    {children}
                </main>
                
            </body>
        </html>
    );
}
